apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: nginx-sample-poc
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 1024m
            memory: 256Mi